version: '3.9'
services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: khd.dev17
      POSTGRES_DB: sentroov
    ports:
      - "5432:5432"
    networks:
      - spring-boot-network
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-boot-network
    depends_on:
      - postgres
    volumes:
      - category-images:/app/images/category-images
      - object-images:/app/images/object-images
volumes:
  category-images:
  object-images:

networks:
  spring-boot-network:
    driver: bridge


#  pgadmin:
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: khd.secure@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: khd.dev17
#    ports:
#      - "8081:80"



#  flask:
#    build:
#      context: ./flask
#      dockerfile: Dockerfile
#    ports:
#      - "5000:5000"
