version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: khd.dev17
      POSTGRES_DB: sentroov
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: khd.secure@gmail.com
      PGADMIN_DEFAULT_PASSWORD: khd.dev17
    ports:
      - 8081:80

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sentroov
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: khd.dev17
    volumes:
      - category-images:/app/images/category-images
      - object-images:/app/images/object-images

  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - 5000:5000

volumes:
  category-images:
  object-images:
