spring:
  datasource:
    password: khd.dev17
    url: jdbc:postgresql://localhost:5432/sentroov
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
server:
  port: 8089
